services:
  db:
    image: "bitnami/postgresql"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: "postgres"
      POSTGRESQL_DATABASE: "journey"
      POSTGRESQL_PASSWORD: "123456"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local